//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой (шаблон Web Forms).
//     Содержит объявления серверных элементов управления страницы Default.aspx.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFormsApp
{
    public partial class Default
    {
        protected global::System.Web.UI.WebControls.TextBox txtName;
        protected global::System.Web.UI.WebControls.Button btnOk;
        protected global::System.Web.UI.WebControls.Button btnClear;
        protected global::System.Web.UI.WebControls.Label lblResult;
        protected global::System.Web.UI.WebControls.Literal litLog;
        protected global::System.Web.UI.WebControls.GridView gvDemo;
        protected global::System.Web.UI.WebControls.TextBox txtA;
        protected global::System.Web.UI.WebControls.DropDownList ddlOp;
        protected global::System.Web.UI.WebControls.TextBox txtB;
        protected global::System.Web.UI.WebControls.Button btnCalc;
        protected global::System.Web.UI.WebControls.Label lblCalc;
    }
}
