//------------------------------------------------------------------------------
// <auto-generated>
//     Объявления серверных элементов управления мастер-страницы Site.Master.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFormsApp
{
    public partial class SiteMaster
    {
        protected global::System.Web.UI.WebControls.ContentPlaceHolder HeadContent;
        protected global::System.Web.UI.HtmlControls.HtmlForm mainForm;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
    }
}
